"""create subscription plan table

Revision ID: 0c36332ce06a
Revises: 3b7f007f17e6
Create Date: 2025-02-25 14:47:44.809434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c36332ce06a'
down_revision: Union[str, None] = '3b7f007f17e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_month_rupee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_year_rupee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_month_dollar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_year_dollar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan_type', sa.Enum('FREE_PLAN', 'PAID_PLAN', 'CUSTOM_PLAN', name='subscriptionplantypeenum'), nullable=False),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DELETED', 'ACTIVE', name='subscriptionplanstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscription_plan_name', 'subscription_plans', ['name'], unique=False)
    op.create_index('idx_subscription_plan_plan_type', 'subscription_plans', ['plan_type'], unique=False)
    op.create_index('idx_subscription_plan_status', 'subscription_plans', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subscription_plan_status', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_plan_type', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_name', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
