"""create role table

Revision ID: 3887cd5762a6
Revises: f8ea4bc0ac32
Create Date: 2025-02-25 14:41:31.963982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3887cd5762a6'
down_revision: Union[str, None] = 'f8ea4bc0ac32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DELETED', 'ACTIVE', name='rolestatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_name', 'roles', ['name'], unique=False)
    op.create_index('idx_role_tenant_id', 'roles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_role_tenant_id', table_name='roles')
    op.drop_index('idx_role_name', table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
