"""create user table

Revision ID: 3b7f007f17e6
Revises: 3887cd5762a6
Create Date: 2025-02-25 14:42:35.822430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7f007f17e6'
down_revision: Union[str, None] = '3887cd5762a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('is_account_owner', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DELETED', 'ACTIVE', 'INACTIVE', 'NOT_VERIFIED', name='userstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_phone_number', 'users', ['phone_number'], unique=False)
    op.create_index('idx_user_tenant_id', 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_tenant_id', table_name='users')
    op.drop_index('idx_user_phone_number', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
