"""added workspace, location, team association table

Revision ID: 639849ef95e4
Revises: 3633c05d33b4
Create Date: 2025-02-25 15:01:09.982067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639849ef95e4'
down_revision: Union[str, None] = '3633c05d33b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workspace_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id')
    )
    op.create_table('user_location_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    op.create_table('user_team_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.add_column('locations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'locations', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('teams', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('workspaces', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workspaces', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'created_by')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'created_by')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'created_by')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'created_by')
    op.drop_table('user_team_association')
    op.drop_table('user_location_association')
    op.drop_table('user_workspace_association')
    # ### end Alembic commands ###
